# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Mountains
logo:               http://blog.krzysztofplonka.pl/images/pages/logo.png
email:              info@krzysztofplonka.pl
description:        Minimal Blog & Magazine Jekyll Theme
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'http://blog.krzysztofplonka.pl' # The base hostname & protocol for your site
my_url:             'http://krzysztofplonka.pl'
name:               Krzysztof Płonka
github_username:    chrismovie
twitter_username:   
instagram_username: 

markdown:  kramdown
permalink: pretty
paginate:  13
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  chris:
    name:             Krzysztof Płonka
    bio:              Front-end developer.
    gravatar:         https://s.gravatar.com/avatar/de2f2c1665c66c2636ebee7d65502bd4?s=150
    email:            info@krzysztofplonka.pl
    website:          http://krzysztofplonka.pl
    github_username:  chrismovie
    twitter_username: 